### PR TITLE
Change profile preflight into postflight

### PR DESCRIPTION
**Pull request by tuxudo**
Profiles can be change by Munki. We want to show the latest changes instead of waiting for next run. Issue brought up by Robban on MacAdmins

### CODE REVIEW

**Comment by bochoven** [comment]
For modules that change from pre= to post flight, rm the old preflight and cache file on install

**Comment by bochoven** [comment]
And maybe kill cfprefsd

**Comment by tuxudo** [comment]
Changes made

**Comment by bochoven** [comment]
On second thought, we don’t need `killall cfprefsd`, sorry about that. I remembered moving another module to postflight, which had an issue with the preferences, and Per Olofsson figured out to fix that

**Comment by tuxudo** [comment]
Closing PR, no longer relevant with v4

**Pull request closed without merging**
